---
title: "Data cleaning & exploratory analysis"
author: "Maria Braeuner"
date: "11/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r LoadPackages, include=FALSE}

library(tidyverse)
library(lubridate)

```

This document details the steps to clean, transform & prepare the raw data from Cyclistic for analysis.

# Import Data

```{r LoadData, include=FALSE}

#Load Data

Nov20 <- read_csv("Data/202011-divvy-tripdata.csv")
Dec20 <- read_csv("Data/202012-divvy-tripdata.csv")
Jan21 <- read_csv("Data/202101-divvy-tripdata.csv")
Feb21 <- read_csv("Data/202102-divvy-tripdata.csv")
Mar21 <- read_csv("Data/202103-divvy-tripdata.csv")
Apr21 <- read_csv("Data/202104-divvy-tripdata.csv")
May21 <- read_csv("Data/202105-divvy-tripdata.csv")
Jun21 <- read_csv("Data/202106-divvy-tripdata.csv")
Jul21 <- read_csv("Data/202107-divvy-tripdata.csv")
Ago21 <- read_csv("Data/202108-divvy-tripdata.csv")
Sep21 <- read_csv("Data/202109-divvy-tripdata.csv")
Oct21 <- read_csv("Data/202110-divvy-tripdata.csv")

#Check all df's have the same structure: check if all column names
#are the same (e.g. would make it easier to merge into one dataframe)
colnames(Nov20) == colnames(Dec20)
colnames(Nov20) == colnames(Jan21)
colnames(Nov20) == colnames(Feb21)
colnames(Nov20) == colnames(Mar21)
colnames(Nov20) == colnames(Apr21)
colnames(Nov20) == colnames(May21)
colnames(Nov20) == colnames(Jun21)
colnames(Nov20) == colnames(Jul21)
colnames(Nov20) == colnames(Ago21)
colnames(Nov20) == colnames(Sep21)
colnames(Nov20) == colnames(Oct21)


```

The data available for each df: `colnames(Nov20)`

With the following data types: `glimpse(Nov20)`

# Merge Data 
```{r MergeData, include=FALSE}

#Merge into one df
cyclistic12 <- rbind(Nov20, Dec20, Jan21, Feb21,
                     Mar21, Apr21, May21, Jun21,
                     Jul21, Ago21, Sep21, Oct21)

head(cyclistic12)
tail(cyclistic12)
dim(cyclistic12) # 5,378,834 x 13

```

# Clean & prepare data for analysis

```{r CleanData, include=FALSE}

#check for data types
glimpse(cyclistic12) #rideable_type & member_casual are as chr, change to factors
cyclistic12$rideable_type <- as.factor(cyclistic12$rideable_type)
cyclistic12$member_casual <- as.factor(cyclistic12$member_casual)
glimpse(cyclistic12) #ok

summary(cyclistic12)
#ended_at includes 3 days of November 2021 (remove)
#end_lat & end_lang have 4831 NA's
#rideable_type categories: classic_bike, docked_bike, electric_bike

length(unique(cyclistic12$start_station_name)) #check how many stations (815)
length(unique(cyclistic12$end_station_name)) #check how many stations (812)

cyclistic <- cyclistic12 %>%
  filter(ended_at <= "2021-11-01 00:00:00")

summary(cyclistic)

#Add new columns for: Day, Month, Year, DayOfWeek (DOW), Season, ride_length
cyclistic$date <- as.Date(cyclistic$started_at) #yyyy-mm-dd
cyclistic$month <- format(as.Date(cyclistic$date), "%m")
cyclistic$day <- format(as.Date(cyclistic$date), "%d")
cyclistic$year <- format(as.Date(cyclistic$date), "%Y")
cyclistic$dow <- format(as.Date(cyclistic$date), "%A")
cyclistic$ride_length <- difftime(cyclistic$ended_at, cyclistic$started_at)


head(cyclistic)
glimpse(cyclistic)

#convert ride_length to numeric
cyclistic$ride_length <- as.numeric(cyclistic$ride_length)

summary(cyclistic) #there are negative ride_length vals.

cyclistic[cyclistic$ride_length <0, ] # 1393 negatives; started_at & ended_at could be inverted, but not sure. 

##Exclude these rows.
final_data <- cyclistic[!cyclistic$ride_length <0, ]

dim(cyclistic) # 5378531 x 18
dim(final_data) # 5377138 x 18
# 5378531 - 5377138 = 1393 = ok

```
